# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ae0f1e5fad735de6969b6a1fd9eab69e395d41af0c1d2d13e844e5351601ce2e24c6164c734a41701e9679ee892018d34980eb862c4fe7e05c05fd4f5089033a

test:
  secret_key_base: 3cadf831922435a50f59ffe2a0b8a0193c3d582903b09e9ae5e0eb68618173aa84ba488538d32c236d358c9d631c6a8652077a6e5c76058bed2a935364fc940d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
